welcomeMessage: >
  Hello World! Welcome to the project! Feel free to explore it.
  Checkout the ReadMe for more details on it.
  Want to contribute? Make an issue or submit a PR.
  Join the Slack channel or the gitter chat for discussions.
  Hope you have a great time here :)
